apiVersion: v1
kind: Service
metadata:
  name: proxy-gateway
spec:
  type: NodePort
  selector:
    name: proxy-gateway-pod
  ports:
    - protocol: TCP
      nodePort: 30036
      port: 5003
      targetPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: weather
spec:
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
  selector:
    name: weather-pod
---
apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  ports:
    - protocol: TCP
      port: 5002
      targetPort: 5002
  selector:
    name: auth-pod
